
@host = https://127.0.0.1:8000
# @host = https://ssd.pingflood.tk
@superuser_username = {{$dotenv SUPERUSER_USERNAME}}
@superuser_password = {{$dotenv SUPERUSER_PASSWORD}}
@staff_username = {{$dotenv STAFF_USERNAME}}
@staff_password = {{$dotenv STAFF_PASSWORD}}
@user_username = {{$dotenv USER_USERNAME}}
@user_password = {{$dotenv USER_PASSWORD}}
@user2_username = {{$dotenv USER2_USERNAME}}
@user2_password = {{$dotenv USER2_PASSWORD}}

@authToken = {{login.response.body.access}}

###
# @name login
POST {{host}}/api/v1/login/
Content-Type: application/json

{
  "username": "{{superuser_username}}",
  "password": "{{superuser_password}}"
}

###
# @name login
POST {{host}}/api/v1/login/
Content-Type: application/json

{
  "username": "{{staff_username}}",
  "password": "{{staff_password}}"
}

###
# @name login
POST {{host}}/api/v1/login/
Content-Type: application/json

{
  "username": "{{user_username}}",
  "password": "{{user_password}}"
}

###
# @name login
POST {{host}}/api/v1/login/
Content-Type: application/json

{
  "username": "{{user2_username}}",
  "password": "{{user2_password}}"
}

####  DRESS ######

### 
GET {{host}}/api/v1/dress/
Authorization: Bearer {{authToken}}


### 
GET {{host}}/api/v1/dress/28bce53b-6c7e-478b-ab85-a5f2066a5278
Authorization: Bearer {{authToken}}

###
POST {{host}}/api/v1/dress/
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "brandType": "VALENTINO",
  "priceInCents": 5000,
  "materialType": "COTTON",
  "colorType": "GRAY",
  "size": 42,
  "description": "ss",
  "deleted": false
}

### 
PUT {{host}}/api/v1/dress/261ca68e-a392-496b-b07a-1e93dd97d645
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "id": "261ca68e-a392-496b-b07a-1e93dd97d645",
  "brandType": "GUCCI",
  "priceInCents": 8000,
  "materialType": "COTTON",
  "colorType": "RED",
  "size": 48,
  "description": "sasas",
  "deleted": false
}

###
DELETE {{host}}/api/v1/dress/c2f8f8f7-933d-44c5-ac2a-3a1116b9a177
Authorization: Bearer {{authToken}}


#### DRESS LOAN ######

### 
GET {{host}}/api/v1/loan
Authorization: Bearer {{authToken}}

### 
GET {{host}}/api/v1/loan/5f9c17cd-ff58-438c-8b89-e97631039f1a
Authorization: Bearer {{authToken}}

###
POST {{host}}/api/v1/loan/
Content-Type: application/json
Authorization: Bearer {{authToken}}

{ 
  "startDate": "2022-12-13",
  "endDate": "2022-12-14",
  "dress": "54416218-701a-4826-a0ad-9fb40348d802",
  "loaner": 2
}

### 
PUT {{host}}/api/v1/loan/7cf29491-de36-4585-bab2-590f25dd7b05
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "id": "7cf29491-de36-4585-bab2-590f25dd7b05",
  "startDate": "2022-12-05",
  "endDate": "2022-12-10",
  "dress": "fba6e9a1-1161-4b97-9a34-e474254bb0d8",
  "loaner": 2,
  "totalPrice": 700.0,
  "loanDurationDays": 7,
  "terminated": false
}

###
DELETE {{host}}/api/v1/loan/89415baa-1498-4b33-a311-9c7fc25b7167
Authorization: Bearer {{authToken}}

#### USER ######

### 
GET {{host}}/api/v1/user
Authorization: Bearer {{authToken}}

### 
GET {{host}}/api/v1/user/3
Authorization: Bearer {{authToken}}

###
POST {{host}}/api/v1/user/
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "dress": "28bce53b-6c7e-478b-ab85-a5f2066a5278",
  "startDate": "2022-11-26",
  "endDate": "2022-12-12",
  "loaner": 2,
  "insertBy": 3
}

### 
PUT {{host}}/api/v1/user/1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "id": "b3819e83-1863-49a2-8871-02acb2eae79d",
  "dress": "28bce53b-6c7e-478b-ab85-a5f2066a5278",
  "startDate": "2022-11-26",
  "endDate": "2022-12-12",
  "loaner": 2,
  "insertBy": 1
}

###
DELETE {{host}}/api/v1/user/4
Authorization: Bearer {{authToken}}

