
@host = https://127.0.0.1:8000
# @host = https://ssd.pingflood.tk
@superuser_username = {{$dotenv SUPERUSER_USERNAME}}
@superuser_password = {{$dotenv SUPERUSER_PASSWORD}}
@staff_username = {{$dotenv STAFF_USERNAME}}
@staff_password = {{$dotenv STAFF_PASSWORD}}
@user_username = {{$dotenv USER_USERNAME}}
@user_password = {{$dotenv USER_PASSWORD}}
@user2_username = {{$dotenv USER2_USERNAME}}
@user2_password = {{$dotenv USER2_PASSWORD}}

@authToken = {{login.response.body.access}}

###
# @name login
POST {{host}}/api/v1/login/
Content-Type: application/json

{
  "username": "{{superuser_username}}",
  "password": "{{superuser_password}}"
}

###
# @name login
POST {{host}}/api/v1/login/
Content-Type: application/json

{
  "username": "{{staff_username}}",
  "password": "{{staff_password}}"
}

###
# @name login
POST {{host}}/api/v1/login/
Content-Type: application/json

{
  "username": "{{user_username}}",
  "password": "{{user_password}}"
}

###
# @name login
POST {{host}}/api/v1/login/
Content-Type: application/json

{
  "username": "{{user2_username}}",
  "password": "{{user2_password}}"
}

####  DRESS ######

### 
GET {{host}}/api/v1/dress/
Authorization: Bearer {{authToken}}


### 
GET {{host}}/api/v1/dress/336bf0a5-59de-4bd3-901b-41f8d8446b6a
Authorization: Bearer {{authToken}}

###
POST {{host}}/api/v1/dress/
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "brandType": "GUCCI",
  "priceInCents": 1234,
  "materialType": "WOOL",
  "colorType": "BLACK",
  "size": 42,
  "description": "ss",
  "deleted": true
}

### 
PUT {{host}}/api/v1/dress/81dc5d50-f259-4c6d-8589-50ed03ab9570
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "id": "81dc5d50-f259-4c6d-8589-50ed03ab9570",
  "brandType": "GUCCI",
  "priceInCents": 13300,
  "materialType": "WOOL",
  "colorType": "BLACK",
  "size": 42,
  "description": "ss",
  "deleted": true
}

###
DELETE {{host}}/api/v1/dress/ea53a166-246a-42d9-80a7-d32290597180
Authorization: Bearer {{authToken}}


#### DRESS LOAN ######

### 
GET {{host}}/api/v1/loan
Authorization: Bearer {{authToken}}

### 
GET {{host}}/api/v1/loan/c97725e3-5a7f-4595-bf0e-93730e33bc6c
Authorization: Bearer {{authToken}}

###
POST {{host}}/api/v1/loan/
Content-Type: application/json
Authorization: Bearer {{authToken}}

{ 
  "startDate": "2025-12-12",
  "endDate": "2025-12-27",
  "dress": "a3ac91b5-d3d1-43b1-ab06-e3fe8a49b160",
  "loaner": 2
}

### 
PUT {{host}}/api/v1/loan/c00e0836-08e4-4e01-9d0a-8d17ec927ad8
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "id": "c00e0836-08e4-4e01-9d0a-8d17ec927ad8",
  "startDate": "2022-12-29",
  "endDate": "2025-12-13",
  "dress": "a3ac91b5-d3d1-43b1-ab06-e3fe8a49b160",
  "loaner": 2,
  "totalPrice": 13697,
  "loanDurationDays": 1109,
  "insertBy": 3,
  "terminated": false
}

###
DELETE {{host}}/api/v1/loan/bf17aea8-2b1d-4b5b-a4c0-5aad167671cc
Authorization: Bearer {{authToken}}

#### USER ######

### 
GET {{host}}/api/v1/user
Authorization: Bearer {{authToken}}

### 
GET {{host}}/api/v1/user/3
Authorization: Bearer {{authToken}}

###
POST {{host}}/api/v1/user/
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "dress": "51cc5d6f-38be-420e-bd75-2b2359d3badf",
  "startDate": "2022-11-26",
  "endDate": "2022-12-12",
  "loaner": 2,
  "insertBy": 3
}

### 
PUT {{host}}/api/v1/user/1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "id": "b3819e83-1863-49a2-8871-02acb2eae79d",
  "dress": "28bce53b-6c7e-478b-ab85-a5f2066a5278",
  "startDate": "2022-11-26",
  "endDate": "2022-12-12",
  "loaner": 2,
  "insertBy": 1
}

###
DELETE {{host}}/api/v1/user/4
Authorization: Bearer {{authToken}}

