# Generated by Django 4.1.3 on 2022-11-25 15:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.IntegerField(choices=[(1, 'GUCCI'), (2, 'ARMANI'), (3, 'VALENTINO')])),
                ('priceInCents', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('material', models.IntegerField(choices=[(1, 'WOOL'), (2, 'SILK'), (3, 'COTTON')])),
                ('color', models.IntegerField(choices=[(1, 'BLACK'), (2, 'BLUE'), (3, 'WHITE'), (4, 'RED'), (5, 'PINK'), (6, 'GRAY')])),
                ('size', models.IntegerField(validators=[django.core.validators.MinValueValidator(38), django.core.validators.MaxValueValidator(60)])),
            ],
        ),
        migrations.CreateModel(
            name='DressLoan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('dress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
