# Generated by Django 4.1.3 on 2022-11-26 07:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "brand",
                    models.IntegerField(
                        choices=[(0, "GUCCI"), (1, "ARMANI"), (2, "VALENTINO")]
                    ),
                ),
                (
                    "priceInCents",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1000000),
                        ]
                    ),
                ),
                (
                    "material",
                    models.IntegerField(
                        choices=[(0, "WOOL"), (1, "SILK"), (2, "COTTON")]
                    ),
                ),
                (
                    "color",
                    models.IntegerField(
                        choices=[
                            (0, "BLACK"),
                            (1, "BLUE"),
                            (2, "WHITE"),
                            (3, "RED"),
                            (4, "PINK"),
                            (5, "GRAY"),
                        ]
                    ),
                ),
                (
                    "size",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(38),
                            django.core.validators.MaxValueValidator(60),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DressLoan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("startDate", models.DateField()),
                ("endDate", models.DateField()),
                (
                    "dress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.dress"
                    ),
                ),
                (
                    "insertBy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loansInsert",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loaner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
