# Generated by Django 4.1.3 on 2022-12-08 09:06

import api.models
import api.validators
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "brand",
                    models.IntegerField(
                        choices=[(0, "GUCCI"), (1, "ARMANI"), (2, "VALENTINO")]
                    ),
                ),
                (
                    "priceInCents",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1000),
                            django.core.validators.MaxValueValidator(1000000),
                        ]
                    ),
                ),
                (
                    "material",
                    models.IntegerField(
                        choices=[(0, "WOOL"), (1, "SILK"), (2, "COTTON")]
                    ),
                ),
                (
                    "color",
                    models.IntegerField(
                        choices=[
                            (0, "BLACK"),
                            (1, "BLUE"),
                            (2, "WHITE"),
                            (3, "RED"),
                            (4, "PINK"),
                            (5, "GRAY"),
                        ]
                    ),
                ),
                (
                    "size",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(38),
                            django.core.validators.MaxValueValidator(60),
                            django.core.validators.StepValueValidator(2),
                        ]
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        max_length=100,
                        validators=[
                            api.validators.descriptionSizeValidator,
                            django.core.validators.RegexValidator(
                                "^[A-Za-z0-9 .,_-]*$",
                                message="Description must be write using allowed chars (A-Za-z0-9 .,_-)",
                            ),
                        ],
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="DressLoan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "startDate",
                    models.DateField(
                        default=datetime.date.today,
                        validators=[api.validators.startDateValidator],
                    ),
                ),
                ("endDate", models.DateField(default=api.models.getTomorrow)),
                ("terminated", models.BooleanField(default=False)),
                (
                    "dress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.dress"
                    ),
                ),
                (
                    "insertBy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loansInsert",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loaner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
