# Generated by Django 4.1.3 on 2022-12-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dressloan',
            name='terminated',
            field=models.BooleanField(default=False),
        ),
    ]
