# Generated by Django 4.1.3 on 2022-11-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dress",
            name="brand",
            field=models.CharField(
                choices=[
                    ("GUCCI", "GUCCI"),
                    ("ARMANI", "ARMANI"),
                    ("VALENTINO", "VALENTINO"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="dress",
            name="color",
            field=models.CharField(
                choices=[
                    ("BLACK", "BLACK"),
                    ("BLUE", "BLUE"),
                    ("WHITE", "WHITE"),
                    ("RED", "RED"),
                    ("PINK", "PINK"),
                    ("GRAY", "GRAY"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="dress",
            name="material",
            field=models.CharField(
                choices=[("WOOL", "WOOL"), ("SILK", "SILK"), ("COTTON", "COTTON")],
                max_length=15,
            ),
        ),
    ]
