# Generated by Django 4.1.3 on 2022-11-26 17:45

import api.models
import api.validators
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dress",
            name="description",
            field=models.TextField(
                default="",
                max_length=500,
                validators=[api.validators.DescriptionValidator],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dress",
            name="priceInCents",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(1000000),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="dress",
            name="size",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(38),
                    django.core.validators.MaxValueValidator(60),
                    django.core.validators.StepValueValidator(2),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="dressloan",
            name="endDate",
            field=models.DateField(default=api.models.getTomorrow),
        ),
        migrations.AlterField(
            model_name="dressloan",
            name="startDate",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
