# Generated by Django 4.1.3 on 2022-12-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_dress_brand_alter_dress_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dress',
            name='dressStatus',
            field=models.BooleanField(default=True),
        ),
    ]
